name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  package-win:
    runs-on: ubuntu-latest
    name: package for Windows
    steps:
    - run: |
        export DIST_DIR=dist/dist-win
        export EXTRA_DIR=dist/extras/dist-win

        rm -rf $DIST_DIR
        mkdir -p $DIST_DIR
        ls
        cp template.blend $DIST_DIR/template.blend
        cp template.blend1 $DIST_DIR/template.blend1
        cp template.esf $DIST_DIR/template.esf
        cp main.py $DIST_DIR/main.py
