name: Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

 jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      name: Package for Windows
      run: |
        export $DIST-DIR=dist/dist-win
        export $EXTRA-DIR=dist/extras/dist-win
        
        rm -rf $DIST-DIR
        mkdir $DIST-DIR
        cp template.blend $DIST-DIR/template.blend
        cp template.blend1 $DIST-DIR/template.blend1
        cp template.esf $DIST-DIR/template.esf
        cp main.py $DIST-DIR/main.py
